### ISSUE TITLE
Portable mode?

### ISSUE THREAD

**Issue by procobain** [CraftySalamander/RTS_Overlay#7] opened 2023-01-08 17:07 UTC
Would you like to implement the portable function in it? Either with a portable.txt or folderportable file?

Hug...

**Comment by CraftySalamander** [comment] 2023-01-10 09:00
Hi.
What do you mean?
You want to have the build order and settings file next to the exe to avoid looking for them in the User folder?

**Comment by procobain** [comment] 2023-02-05 06:45
@CraftySalamander 

No, I want the overlay configuration file to be in the same folder as the game, as if it were a portable program.

I have two accounts, one I only choose civs, the other one I only play random. My accounts scores are different for that.

So I want to have two RTS Overlays, one for each account, so I don't have to write my nickname every time I switch accounts.

**Comment by CraftySalamander** [comment] 2023-02-06 08:10
The suggestion I was making above should solve this.
With the configuration file next to the exe, you can put the RTS Overlay anywhere and have several instances of them (each one could look at the configuration file next to it).
I can see if I could integrate this in the next release.

**Comment by CraftySalamander** [comment] 2023-02-07 07:54
For the country flag, could you give me more details?

I am fetching the country information from aoe2.net.
I do not have the issue on my side.  When a flag is not there, it is not available on aoe2.net either.

Can you give me a username to look for, where you do not get the country flag with RTS Overlay, but the info is available on aoe2.net?

**Comment by CraftySalamander** [comment] 2023-03-22 15:23
Hi.
These 2 issues (local configuration and missing data from aoe2.net) should be solved with latest release (1.5.0).
See the [changelog](https://github.com/CraftySalamander/RTS_Overlay/blob/master/Changelog.md).

In short, create a folder called `local_config` at the root of the folder. If this folder exists, the app will use it instead of the user directory (so, you can have different configurations with different folders).

**Comment by CraftySalamander** [comment] 2023-04-04 12:21
Closing the issue (assuming the problem is solved).

**Closed by CraftySalamander** 2023-04-04 12:21 UTC
